### ISSUE TITLE
Is there any code for love wave analyze and  forwarding?

### ISSUE THREAD

**Issue by xichaoqiang** [HiroUgoto/PyArray#1]
Hello,

Thanks for sharing this package.

Is there any code for Love wave analyze and  forwarding?

Best regards,
Xi

**Comment by HiroUgoto** [comment]
Hello, 

I'm sorry, but Love wave is not available at the current version.

Regards,
Hiro

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.
