### ISSUE TITLE
A question about set_F_matrix subroutine  in rayleigh.f90

### ISSUE THREAD

**Issue by xichaoqiang** [HiroUgoto/PyArray#2]
![image](https://user-images.githubusercontent.com/30900789/150263327-358a71b6-9817-4787-aedd-8c6efdd71d4f.png)
I compared the set_F_matrix subroutine with eq.(7.56) and I noticed that the left matrix does not appear. What is the reason for this?

**Comment by HiroUgoto** [comment]
Hi, 

This is the radiation term. If the interface locates at z=0, the term is absent.

Regards,
Hiro

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.
